Repository wintercms/wn-translate-plugin, pull requests merged in 2022-03, with the labels that each got.

#22 MigrateMessageCode to manage new case sensitive md5 hash
  models/Message.php
  tests/unit/models/MessageTest.php
  updates/v2.1.0/migrate_message_code.php
Labels: Status: Completed, Type: Enhancement

#23 Fixed incorrect column name
  updates/v1.3.1/add_sort_order.php
Labels: Status: Completed, Type: Maintenance

#25 Message::firstWhere() can be NULL
  updates/v2.1.0/migrate_message_code.php
Labels: Status: Completed, Type: Maintenance

#27 Check if cms is loaded before scanning
  updates/v2.1.0/migrate_message_code.php
Labels: Type: Unconfirmed Bug, Status: Review Needed
