Repository wintercms/wn-translate-plugin, pull requests merged in 2023-04, with the labels that each got.

#57 Refactor code & add support for Winter.Sitemap
  Plugin.php
  behaviors/TranslatableCmsObject.php
  behaviors/TranslatableModel.php
  behaviors/TranslatablePage.php
  behaviors/TranslatablePageUrl.php
  classes/EventRegistry.php
  classes/LocaleMiddleware.php
  classes/MLCmsObject.php
  classes/MLContent.php
  classes/MLPage.php
  classes/MLStaticPage.php
  classes/ThemeScanner.php
  classes/TranslatableBehavior.php
  classes/Translator.php
  components/AlternateHrefLangElements.php
  components/LocalePicker.php
  config/config.php
  console/ScanCommand.php
  controllers/Locales.php
  controllers/Messages.php
  formwidgets/MLMarkdownEditor.php
  formwidgets/MLMediaFinder.php
  formwidgets/MLRepeater.php
  formwidgets/MLRichEditor.php
  formwidgets/MLText.php
  formwidgets/MLTextarea.php
  models/Attribute.php
  models/Locale.php
  models/Message.php
  models/MessageExport.php
  models/MessageImport.php
  routes.php
  traits/MLControl.php
Labels: Status: Completed, Type: Enhancement

#59 Update controllers/Locales.php
  controllers/Locales.php
Labels: Status: Accepted, Type: Maintenance

#60 Trailing slash on void elements has no effect
  components/alternatehreflangelements/default.htm
Labels: Status: Completed, Type: Maintenance
