Repository wintercms/wn-translate-plugin, pull requests merged in 2024-03, with the labels that each got.

#70 prevents browser autofill off translated inputs
  traits/mlcontrol/partials/_locale_values.htm
Labels: Status: Completed, Type: Maintenance

#52 Add validation for translated strings
  classes/TranslatableBehavior.php
Labels: Status: Review Needed, Type: Enhancement

#78 fixes error when using translatabe model behavior and lang() shorthand
  classes/TranslatableBehavior.php
Labels: Status: Accepted, Type: Maintenance

#73 Improved ML button styling
  assets/css/multilingual.css
  assets/less/multilingual.less
  formwidgets/MLTextarea.php
  formwidgets/mlmarkdowneditor/assets/js/mlmarkdowneditor.js
  formwidgets/mlricheditor/assets/js/mlricheditor.js
  formwidgets/mltextarea/assets/js/mltextarea.js
  formwidgets/mltextarea/partials/_mltextarea.htm
Labels: Status: Completed, Type: Maintenance
